sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '5.3.0'
before_install:
  - npm i -g npm@^3.0.0
before_script:
  - npm prune
after_script:
  - npm run coveralls
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
